name: Sync Fork

on:
  schedule:
  - cron: "0 0 * * *"  # nightly
  workflow_dispatch:   # enable manual trigger
  push:  # TODO: remove after development
    branches:
    - feature/fork-sync

env:
  PR_MESSAGE_FOR_BOTH_JOBS: "Created by [${{ github.repository }} CI](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) (*${{ github.job }}* job), after syncing the fork from upstream."  # must be generic/dynamic enough to suit both jobs  # TODO: test link

jobs:
  sync-fork:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Lookup most recent release branch
      id: lookup-most-recent-release-branch
      run: |
        git fetch --all
        most_recent_release_branch=$(git branch --remotes --sort refname | grep network-operator- | tail -n 1 | cut -d "/" -f 2-)
        echo most_recent_release_branch=$most_recent_release_branch >> $GITHUB_ENV
        echo most_recent_release_branch=$most_recent_release_branch >> $GITHUB_OUTPUT
    - uses: tgymnich/fork-sync@v1.8
      with:
        owner: k8snetworkplumbingwg  # upstream
        head: master                 # upstream
        base: ${{ env.most_recent_release_branch }}  # downstream  # TODO: also sync master
        pr_title: "task: Sync from upstream"
        pr_message: "${{ env.PR_MESSAGE_FOR_BOTH_JOBS }}"
        ignore_fail: true  # TODO: add a condition to this step, in order to avoid the 4 minute wait when *no changes in upstream*
      timeout-minutes: 1       # TODO: remove this before merging, in order to maintain informative output message
      continue-on-error: true  # TODO: remove this before merging, in order to maintain informative output message
    outputs:
      most_recent_release_branch: ${{ steps.lookup-most-recent-release-branch.outputs.most_recent_release_branch }}

  update-network-operator-values:  # TODO: ask ivan: consider doing this only if the CI (build) passes, and not as early as...here!
    runs-on: ubuntu-latest
    needs: sync-fork
    env:
      MOST_RECENT_RELEASE_BRANCH: ${{ needs.sync-fork.outputs.most_recent_release_branch }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # TODO: may need to add to repo settings
    steps:
    - uses: actions/checkout@v4
      with:
        repository: maze88/network-operator  # TODO: change org to Mellanox before merging
        sparse-checkout-cone-mode: false
        sparse-checkout: deployment/network-operator/values.yaml
    - name: Update image tags in network-operator values
      run: |
        git config user.name  svc-cloud-orch-ci
        git config user.email svc-cloud-orch-ci@nvidia.com
        git checkout -b feature/update-sriov-to-${MOST_RECENT_RELEASE_BRANCH:17}-${{ github.run_id }}  # TODO: remove run id suffix before merging
        sed -Ei "s/:network-operator-.+/:$MOST_RECENT_RELEASE_BRANCH/g" deployment/network-operator/values.yaml
        git commit -am "task: update SR-IOV images tags to ${MOST_RECENT_RELEASE_BRANCH:17} in chart values"
        git diff HEAD~1 --unified=0
        # git push --set-upstream origin $(git branch --show-current)
    - name: Create pull request  # TODO: run idempotently or conditionally if diff
      run: |
        gh pr create \
          --repo Mellanox/network-operator \
          --base master \
          --head $(git branch --show-current) \
          --fill \
          --dry-run --body "$PR_MESSAGE_FOR_BOTH_JOBS"  # TODO: remove dry-run when ready
