name: Sync Fork

on:
  schedule:
  - cron: '0 * * * *'  # every 60 minutes
  workflow_dispatch:   # enable manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: tgymnich/fork-sync@v1.8
      with:
        owner: k8snetworkplumbingwg  # upstream
        head: master                 # upstream
        base: master                 # downstream
