name: Fork Sync

on:
  schedule:
  - cron: '0 0 * * *'  # nightly
  workflow_dispatch:   # enable manual trigger

jobs:
  lookup-most-recent-release-branch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Lookup most recent release branch
      id: lookup-most-recent-release-branch
      run: |
        git fetch --all
        echo most_recent_release_branch=$(git branch --remotes --sort refname | grep network-operator- | tail -n 1 | cut -d '/' -f 2-) >> $GITHUB_OUTPUT
    outputs:
      most_recent_release_branch: ${{ steps.lookup-most-recent-release-branch.outputs.most_recent_release_branch }}

  sync-fork:
    runs-on: ubuntu-latest
    needs: lookup-most-recent-release-branch
    strategy:
      fail-fast: false
      matrix:
        branch:
        - master
        - ${{ needs.lookup-most-recent-release-branch.outputs.most_recent_release_branch }}
    steps:
    - uses: actions/checkout@v4
      if: ${{ matrix.branch != '' }}
      with:
        ref: ${{ matrix.branch }}
        # fetch-depth: 10
    - name: Sync
      if: ${{ matrix.branch != '' }}
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN_NVIDIA_CI_CD }}
      run: |
        git config user.name  nvidia-ci-cd
        git config user.email svc-cloud-orch-gh@nvidia.com
        git remote add upstream https://github.com/k8snetworkplumbingwg/sriov-network-operator.git

        git status; git branch  # debug
        git checkout ${{ matrix.branch }}  # TODO: see if redundant when working with `ref` in checkout step
        git status; git branch  # debug
        git log --oneline  -n 4  # debug
        git pull upstream master
        git log --oneline -n 10  # debug

        # git push --force origin HEAD  # TODO: uncomment only after testing commands above

